version: "3"
services:
  strapi:
    container_name: strapi
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      REDIS_HOST: redis
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads

    ports:
      - "1337:1337"
    depends_on:
      - redis
    networks:
      - strapi-net

  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - strapi-net

volumes:
  strapi-data:

networks:
  strapi-net:
    driver: bridge
